map_type: costmap

obstacle_range: 1.0 # 2.0
raytrace_range: 2.0 # 3.0

transform_tolerance: 0.2 # 0.0

robot_radius: 0.3 # 0.0
inflation_radius: 0.5 # 0.0
cost_scaling_factor: 5.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
