home:
  tx: 0.0
  ty: 0.0
  tz: 0.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  qw: 1.0


pick:
  tx: 1.5
  ty: 0.0
  tz: 0.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  qw: 1.0

place:
  tx: 3.5
  ty: 3.5
  tz: 0.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  qw: 1.0